name: setup

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run custom Apiable GitHub Action
        id: run-apiable-action
        uses: ./
        with:
          api_key: ${{ secrets.APIABLE_DEVELOPER_PORTAL_CLIENT_ID }}
          api_secret: ${{ secrets.APIABLE_DEVELOPER_PORTAL_CLIENT_SECRET }}
          api_url: "https://dev.api.apiable.io"
          open_api_spec_url: "https://dev-api.apiable.io/api/int/public/v3/api-docs"
          planid: "659fa46a2f08a41f65664bba"

      # Step 3: Get the output from the custom action
      - name: Get Action Output
        run: |
          echo "Action Response: ${{ steps.run-apiable-action.outputs.response }}"